### ISSUE TITLE
can't generate from FSM

### ISSUE THREAD

**Issue by j2l** [OpenPonk/fsm-editor#3]
I starred because it seems cool, but I didn't find how to generate, or at least export as some JSON format a FSM diagram.

**Comment by JanBliznicenko** [comment]
Hello, unfortunately, there is no easy way to export the whole diagram to some generally used format, like graphml, json or anything like that. Persistence is solved using .opp project files that are (renamed) .zip archives, but the inner files containing data are split into separate model (in graphml format with .ston extension) and diagram (in json format), as there can be multiple diagram views over single model.

**Comment by j2l** [comment]
OK, too bad. thanks anyway for the detailed replied.
